---
- name: Listen for events on a Kafka topic
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: 127.0.0.1
        port: 9092
        topic: eda-topic

  rules:
    - name: Cheers at Ansible from a Kafka topic!
      condition: event.body.name == "greeting"
      actions:
        - debug:
        - run_playbook:
            name: eda-playbook-kafka.yml
