---
- name: Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: Enable AlertManager listener
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Let Ansible print information about the alert
      condition: event.payload.status == "firing" or event.payload.status == "resolved"
      actions:
        - debug:
        - run_playbook:
            name: eda-playbook-alertmanager.yml
