---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Cheers at Ansible from a webhook!
      condition: event.payload.name == "greeting"
      actions:
        - debug:
        - run_playbook:
            name: eda-playbook-webhook.yml
